#----------------------------------------------------------------------------------------Pokemon library-----------------
all_Types_Eng = {"Normal","Fighting","Flying","Poison","Ground","Rock","Bug",
                 "Ghost","Steel","Fire","Water","Grass","Electric",
                 "Psychic","Ice","Dragon","Dark","Fairy"} #Different Types of Pokemon 

Weakdic = {#Attack:Defender --->,,This is not super effective!"
        "Normal" : [],
        "Psychic":["Fighting", "Poison"],
        "Bug":["Psychic","Dark","Grass"],
        "Fighting":["Normal","Rock","Steel","Ice","Dark"],
        "Ice":["Flying","Ground","Grass","Dragon"],
        "Fairy":["Fighting","Dragon","Dark"],
        "Poison":["Grass","Fairy"],
        "Ghost":["Ghost","Psychic"],
        "Grass":["Ground","Rock","Water"],
        "Dark":["Ghost","Psychic"],
        "Rock":["Flying","Bug","Fire","Ice"],
        "Fire":["Bug","Steel","Grass","Ice"],
        "Flying":["Fighting","Bug","Grass"],
        "Dragon":["Dragon"],
        "Ground":["Poison", "Rock","Steel","Fire","Electric"],
        "Electric":["Flying","Water"],
        "Steel":["Rock","Ice","Fairy"],
        "Water":["Ground","Rock","Fire"],
        }
        
Resdic = {#Attack:Defender --->,,This is not very effective"
        "Normal" : ["Rock","Steel"],
        "Psychic":["Psychic","Steel"],
        "Bug":["Fire","Fighting","Poison","Flying","Ghost","Steel"],
        "Fighting":["Poison","Flying","Psychic","Bug","Fairy","Ghost"],
        "Ice":["Fire","Water","Ice","Steel"],
        "Fairy":["Fire","Fighting","Steel"],
        "Poison":["Poison","Ground","Rock","Ghost","Steel"],
        "Ghost":["Normal","Steel"],
        "Grass":["Fire","Grass","Poison","Flying","Bug","Dragon"],
        "Dark":["Fighting","Dark","Fairy"],
        "Rock":["Fighting","Ground","Steel"],
        "Fire":["Fire","Water","Rock","Dragon"],
        "Flying":["Electric","Rock","Steel"],
        "Dragon":["Steel","Fairy"],
        "Ground":["Grass","Flying","Bug"],
        "Electric":["Grass","Electric","Ground","Dragon"],
        "Steel":["Fire","Water","Electric","Steel"],
        "Water":["Water","Grass","Dragon"],
        }
Nothdic = { #Attack:Defender --->,,This Attack hasn't an effect"
    "Normal":["Ghost"],
    "Psychic":["Dark"],
    "Bug":[],
    "Fighting":["Ghost"],
    "Ice":[],
    "Fairy":[],
    "Poison":["Steel"],
    "Ghost":["Normal"],
    "Grass":[],
    "Dark":[],
    "Rock":[],
    "Fire":[],
    "Flying":[],
    "Dragon":["Fairy"],
    "Ground":["Flying"],
    "Electric":["Ground"],
    "Steel":[],
    "Water":[],
    }
